# CodeRabbit configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: en-US

early_access: true

reviews:
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
